name: Fullstack Frontend Docker Image Creation
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - fullstack/fullstack_frontend/**
jobs:
  CreateDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Create Docker Image"
        run: |
          cd fullstack/fullstack_frontend
          docker build -t fullstack_frontend:$(git rev-parse --short HEAD)_$(TZ="Asia/Kolkata" date +'%Y%m%d_%H%M%S') .
          docker image ls
      - name: "Login to AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"