name: Fullstack Frontend Docker Image Creation
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - fullstack/fullstack_frontend/**
jobs:
  CreateDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Create Docker Image"
        run: |
          cd fullstack/fullstack_frontend
          docker build -t fullstack_frontend:latest .
          docker image ls