name: Fullstack Frontend Docker Image Creation
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - fullstack/fullstack_frontend/**
jobs:
  CreateDockerImage:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Login to AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
            IMAGE_TAG: fullstack_frontend_${{ github.sha::0:7 }}_$(TZ="Asia/Kolkata" date +'%Y%m%d_%H%M%S')
        run: |
          cd fullstack/fullstack_frontend
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker image ls
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG