name: Infrastructure Deployment on AWS
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - iac/**
jobs:
  Terraform_Apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Login to AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: "us-east-1"

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Version
        run: terraform --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
